source 'https://rubygems.org'
ruby "2.4.4"

gem 'capybara', '2.7.1'
gem 'selenium-webdriver', '2.47.1'
gem 'capybara-screenshot', '1.0.11'
gem 'rspec', '2.99.0'
gem 'fuubar', '1.3.3'
gem 'rspec-rerun', '0.3.1'
gem 'site_prism', '2.9'
gem 'gibberish', '2.1.0'