source 'https://rubygems.org'
ruby "2.0.0"

gem 'capybara', '2.7.1'
gem 'selenium-webdriver', '~> 2.47.1'
gem 'capybara-screenshot', '~> 1.0.11'
gem 'rspec', '~> 3.9.0'
gem 'fuubar'
gem 'rspec-rerun'
gem 'site_prism', '2.9'
gem 'gibberish'