source 'https://rubygems.org'
ruby "2.7.1"

gem 'capybara', '3.5'
gem 'selenium-webdriver', '3.141.0'
gem 'capybara-screenshot', '~> 1.0.24'
gem 'rspec', '~> 3.9.0'
gem 'fuubar', '2.5.0'
gem 'rspec-rerun', '1.1.0'
gem 'site_prism', '2.17'
gem 'gibberish', '2.1.1'
gem 'pry-byebug', '3.9.0'